### ISSUE TITLE
cannot find `cal3BV` when compiling python package

### ISSUE THREAD

**Issue by ImpleLee** [eee555/ms_toollib#1]
https://github.com/eee555/ms_toollib/blob/81cc99ce35e25049c3d924235dd3163fc3d74da2/python_package/src/lib.rs#L60

The renaming commit 865013d appears to lack this specific calling.

**Comment by eee555** [comment]
Thank you. A new commit has just been pushed.
I changed 3BV to bbbv because it fits the snake case.
